exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('chapters').del()
    .then(() => knex('lesson_chapters').del())
    .then(function () {
      // Inserts seed entries
      return knex('chapters').insert([
        {
          id: 'chapter1',
          name: 'A Chapter',
          slug: 'a-chapter',
          description: 'An H5P Chapter.',
          status: 'published',
          lesson_id: 'lesson1',
          creator_id: 'user1',
          content_type: 'h5p',
          content_uri: '/uploads/h5p/chapter1',
          created_at: '2017-12-20 19:17:10',
          updated_at: '2017-12-20 19:17:10',
          approved: true,
          tags: ['highschool', 'university'],
        },
        {
          'id': 'chapter2',
          'name': 'Kelley',
          'slug': 'Elisa',
          'description': 'consectetur',
          creator_id: 'user1',
          'status': 'published',
          'lesson_id': 'basics1',
          creator_id: 'user1',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter2',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          approved: true,
          tags: ['highschool', 'university'],
        },
        {
          'id': 'chapter3',
          'name': 'Ethel',
          'slug': 'Tonya',
          'description': 'cupidatat',
          creator_id: 'user1',
          'status': 'published',
          'lesson_id': 'basics2',
          creator_id: 'user1',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter3',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          tags: ['university'],
          approved: false,
        },
        {
          'id': 'chapter4',
          'name': 'Montoya',
          'slug': 'Myra',
          'description': 'qui',
          'status': 'published',
          creator_id: 'user1',
          'lesson_id': 'basics2',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter4',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          approved: true,
          tags: ['highschool', 'university'],
        },
        {
          'id': 'chapter5',
          'name': 'Montoya',
          'slug': 'Myra',
          creator_id: 'user1',
          'description': 'qui',
          'status': 'published',
          'lesson_id': 'basics2',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter5',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          approved: true,
          tags: ['primary', 'university'],
        },
        {
          'id': 'chapter6',
          'name': 'Montoya',
          'slug': 'Myra',
          'description': 'qui',
          'status': 'published',
          creator_id: 'user1',
          'lesson_id': 'basics2',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter5',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          approved: true,
          tags: ['primary', 'university'],
        },
        {
          'id': 'chapter6',
          'name': 'Montoya',
          'slug': 'Myra',
          'description': 'qui',
          'status': 'published',
          'lesson_id': 'basics2',
          creator_id: 'user1',
          'content_type': 'h5p',
          'content_uri': '/uploads/h5p/chapter5',
          'created_at': '2017-12-20 19:17:10',
          'updated_at': '2017-12-20 19:17:10',
          approved: true,
          tags: ['primary', 'university'],
        }
      ]);
    });
};